// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-09-01 14:56:49.306886 +0900 JST m=+0.024272500

package docs

import (
	"bytes"
	"encoding/json"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "このアプリで試そうと思っていることは下記。\n- ドキュメント自体がどこまで手軽にかけるか\n- 認証周りは動作するか\n- 共通レスポンスなどが簡単にかけるか\n- ドキュメントのバージョン管理がうまくできるか\n- CIによるビルドができるかどうか",
        "title": "OpenAPIドキュメントのお試し",
        "contact": {},
        "license": {},
        "version": "1.0"
    },
    "host": "localhost:8000",
    "basePath": "/api",
    "paths": {
        "/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "全てのユーザの一覧を取得する。",
                "produces": [
                    "appliction/json"
                ],
                "tags": [
                    "User",
                    "Reference"
                ],
                "summary": "ユーザの一覧を取得する",
                "parameters": [
                    {
                        "type": "string",
                        "description": "APIバージョンヘッダ",
                        "name": "X-API-VERSION",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常に処理された場合",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.UsersResponse"
                        }
                    },
                    "400": {
                        "description": "共通ヘッダーなどが設定されていない場合",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "description": "Details 詳細",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "名前は必須です。",
                        " 年齢は必須です。"
                    ]
                },
                "summary": {
                    "description": "Summary 概要",
                    "type": "string",
                    "example": "入力データに不備があります。"
                }
            }
        },
        "api.UserResponse": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "Age 年齢",
                    "type": "integer",
                    "example": 24
                },
                "id": {
                    "description": "ID ユーザのID",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "Name 名前",
                    "type": "string",
                    "example": "テスト 太郎"
                }
            }
        },
        "api.UsersResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Count 件数\nデータがない場合は0。",
                    "type": "integer",
                    "example": 3
                },
                "result": {
                    "description": "Result 結果のリスト\nデータがない場合は空のリストが返る。",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.UserResponse"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "ユーザに関するAPI",
            "name": "User"
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{ Schemes: []string{}}

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface {}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
